#ifndef LONGSCROLLQT_GLOBAL_H
#define LONGSCROLLQT_GLOBAL_H

#include <QtCore/QtGlobal>

#if defined(LONGSCROLLQT_LIBRARY)
#  define LONGSCROLLQT_EXPORT Q_DECL_EXPORT
#else
#  define LONGSCROLLQT_EXPORT Q_DECL_IMPORT
#endif

#ifndef LONGSCROLLQT_NAMESPACE
#  define LONGSCROLLQT_NAMESPACE       longscroll
#endif
#define LONGSCROLLQT_NAMESPACE_BEGIN namespace LONGSCROLLQT_NAMESPACE {
#define LONGSCROLLQT_NAMESPACE_END   }
#define LONGSCROLLQT_NAMESPACE_USING using namespace LONGSCROLLQT_NAMESPACE;

#endif // LONGSCROLLQT_GLOBAL_H
